---
- name: Create EC2 instance
  hosts: local
  tags: always
  vars_prompt:
    - name: ec2_admin_ip
      prompt: IP to allow to connect to the Docker daemon in CIDR
      default: 87.138.108.187/24
      private: no
  vars:
    ec2_group: sota-docker-hub
  pre_tasks:
    - include_vars: ../docker-launcher.yml
  tasks:
    - name: Create security group
      local_action:
        module: ec2_group
        name: "{{ ec2_group }}"
        description: "Security group for a remote docker host"
        region: "{{ ec2.region }}"
        state: present
        rules:
          - proto: all
            from_port: 0
            to_port: 65535
            cidr_ip: "{{ ec2_admin_ip }}"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

    - name: get fresh discovery url
      raw: curl -s https://discovery.etcd.io/new
      register: discovery_output

    - name: Save the discovery url as fact
      set_fact: discovery_url={{ discovery_output.stdout }}

    - name: Create ec2 instance
      local_action:
        module: ec2
        key_name: "{{ ec2.key }}"
        group: "{{ ec2_group }}"
        instance_type: t2.medium
        image: "{{ ec2.image }}"
        region: "{{ ec2.region }}"
        wait: no
        exact_count: 1
        user_data: "{{ lookup('template', 'cloud-config.j2') }}"
        count_tag:
          Name: sota-docker-hub
        instance_tags:
          Name: sota-docker-hub
          type: coreos
