---
services:
  - name: mysql
    version: "{{ mariadb_version }}"
    repo: mariadb
    ports:
      - 3306
    wait:
      port: 3306
      delay: 30
    env:
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_user_password }}"
      MYSQL_DATABASE: "{{ db_database_name }}"

  - name: rvi_server
    version: server
    repo: advancedtelematic/rvi:server
    ports:
      - 8801
      - 8802
      - 8803
      - 8804
      - 8805
      - 8806
      - 8807
    wait:
      port: 8801
      delay: 5
    attach: true

  - name: rvi_client
    version: client
    repo: advancedtelematic/rvi:client
    ports:
      - 8901
      - 8907
      - 8908
    links:
      - rvi_server
    attach: true
